### ISSUE TITLE
Double square brackets seems to cause some issues with JIRA's own GitHub integration

### ISSUE THREAD

**Issue by dobesv** [hjdarnel/jira-markdown-link#1]
When it inserts something like `[[BUG-123]] Some description of the bug` the JIRA GitHub integration rewrites it so that the inner `[BUG-123]` becomes a link and so it renders like `[BUG-123](https://xxx.jira.atlassian.com/browse/BUG-123` instead of just a link.  It would be nice if it would insert in a different format, like maybe just one set of square brackets?  Or a customizable format?

**Comment by hjdarnel** [comment]
Since I rarely use this extension, I just tweaked it as you requested to only use one set of brackets. Fixed in https://github.com/hjdarnel/jira-markdown-link/releases/tag/v0.0.2 which I've sent to the Chrome store for review/release.
